AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'lib/kubemq/proto/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'kubemq.gemspec'
  Max: 40

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ParameterLists:
  Max: 10

Style/Documentation:
  Enabled: false
