# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: kubemq.proto for package 'kubemq'

require 'grpc'
require_relative 'kubemq_pb'

module Kubemq
  module Kubemq
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'kubemq.kubemq'

      rpc :SendEvent, ::Kubemq::Event, ::Kubemq::Result
      rpc :SendEventsStream, stream(::Kubemq::Event), stream(::Kubemq::Result)
      rpc :SubscribeToEvents, ::Kubemq::Subscribe, stream(::Kubemq::EventReceive)
      rpc :SubscribeToRequests, ::Kubemq::Subscribe, stream(::Kubemq::Request)
      rpc :SendRequest, ::Kubemq::Request, ::Kubemq::Response
      rpc :SendResponse, ::Kubemq::Response, ::Kubemq::Empty
      rpc :SendQueueMessage, ::Kubemq::QueueMessage, ::Kubemq::SendQueueMessageResult
      rpc :SendQueueMessagesBatch, ::Kubemq::QueueMessagesBatchRequest, ::Kubemq::QueueMessagesBatchResponse
      rpc :ReceiveQueueMessages, ::Kubemq::ReceiveQueueMessagesRequest, ::Kubemq::ReceiveQueueMessagesResponse
      rpc :StreamQueueMessage, stream(::Kubemq::StreamQueueMessagesRequest), stream(::Kubemq::StreamQueueMessagesResponse)
      rpc :AckAllQueueMessages, ::Kubemq::AckAllQueueMessagesRequest, ::Kubemq::AckAllQueueMessagesResponse
      rpc :Ping, ::Kubemq::Empty, ::Kubemq::PingResult
      rpc :QueuesDownstream, stream(::Kubemq::QueuesDownstreamRequest), stream(::Kubemq::QueuesDownstreamResponse)
      rpc :QueuesUpstream, stream(::Kubemq::QueuesUpstreamRequest), stream(::Kubemq::QueuesUpstreamResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
